# This is a Mosquitto configuration file that creates a listener on port 1883
# that allows unauthenticated access.

## User ##
user root

## Data ##
persistence true
persistence_location /mosquitto/data/
persistence_file mosquitto.db
persistent_client_expiration 1d
autosave_interval 60

#i Logging ##
connection_messages true
log_type all
log_dest stdout

listener 1883
password_file /mosquitto/config/passwd
allow_anonymous false

listener 9883
protocol http_api
http_dir /usr/share/mosquitto/dashboard
